# Generated by Django 4.2.2 on 2023-07-30 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='customer_profile_pic')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Freelance_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter your full name', max_length=255)),
                ('location', models.CharField(blank=True, help_text='E.g. city,coutry Dhaka, Bangladesh', max_length=255, null=True)),
                ('set_available', models.CharField(blank=True, choices=[('Available Now', 'Available Now'), ('I am going on vacation', 'I am going on vacation')], default='Available Now', max_length=255, null=True)),
                ('title', models.CharField(help_text='E.g. Django developer, javascript developer', max_length=255)),
                ('hourly_rate', models.CharField(help_text='E.g. $15', max_length=10)),
                ('description', models.TextField(help_text='E.g. within 2000 characters', max_length=2000)),
                ('other_experience', models.CharField(blank=True, help_text='E.g. within 1000 characters', max_length=1000, null=True)),
                ('profile_pic', models.ImageField(upload_to='freelance_profile_pricture')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.freelance_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(help_text='E.g. python, django, react', max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.freelancerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='other.category')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ImageField(upload_to='ferrlancer_portfolio')),
                ('title', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.freelancerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order_date',),
            },
        ),
        migrations.CreateModel(
            name='HiredFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(help_text='E.g. within 500 characters', max_length=500)),
                ('job_requirement', models.TextField()),
                ('delivery_date', models.DateField(blank=True, help_text='E.g. YYYY-MM-DD format', null=True)),
                ('project_price', models.DecimalField(decimal_places=2, help_text='E.g. 100.00', max_digits=10)),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Accepted', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.freelancerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=500)),
                ('join_date', models.CharField(help_text='E.g. March, 2023', max_length=255)),
                ('short_bio', models.CharField(blank=True, help_text='E.g. about company', max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.freelancerprofile')),
            ],
        ),
    ]
