# Generated by Django 4.2.2 on 2023-07-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_customer_orderplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profile_pic'),
        ),
    ]
