# Generated by Django 4.2.2 on 2023-07-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=100),
        ),
    ]
