# Generated by Django 4.2.1 on 2023-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(max_length=300)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
