# Generated by Django 4.2.1 on 2023-05-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refbooks',
            name='pdf',
            field=models.FileField(upload_to='ref_book'),
        ),
    ]
