# Generated by Django 4.2.1 on 2023-05-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_refbooks_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refbooks',
            old_name='name',
            new_name='book_name',
        ),
    ]
