# Generated by Django 4.2.1 on 2023-05-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_addprojects_nuquestion_programmingcontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='nuquestion',
            name='question_type',
            field=models.CharField(choices=[('Mid Question', 'Mid Question'), ('Year Question', 'Year Question')], max_length=100),
        ),
    ]
