# Generated by Django 4.2.2 on 2023-07-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_ourteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmingcontest',
            old_name='schedule',
            new_name='duration',
        ),
    ]
