# Generated by Django 4.2.2 on 2023-07-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_schedule_programmingcontest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprojects',
            name='github_code',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='addprojects',
            name='live_demo',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
